name: system_info3
description: Easy access to essential system information, including details about your system's architecture, kernel, memory, operating system, CPU, and user environment
version: 4.0.1
homepage: https://github.com/dev-kasibhatla/system_info3
documentation: https://github.com/dev-kasibhatla/system_info3
repository: https://github.com/dev-kasibhatla/system_info3
issue_tracker: https://github.com/dev-kasibhatla/system_info3/issues
environment: 
  sdk: '>=2.19.0 <4.0.0'
dependencies: 
  globbing: ^1.0.0
  path: ^1.8.0
dev_dependencies: 
  lint_hard: ^3.0.0
platforms:
  android:
  linux:
  macos:
  windows: